//! THE gate for the do-no-harm rule (AGENTS.md; features.md 4.5): loading
//! then saving a foreign file must be BYTE-IDENTICAL — encoding, BOM, line
//! endings and trailing newline all preserved.
//!
//! Driven by crates/core/tests/fixtures/manifest.json (28 byte-exact
//! fixtures generated by xtask). A fixture added to the manifest becomes a
//! checked case without editing this file. The manifest MUST exist and MUST
//! be non-empty: a missing or empty manifest fails these tests — a skipped
//! gate looks identical to a green one.
//!
//! Honest scope note: the 28 manifest cases run in ONE looping test
//! (`every_manifest_fixture_round_trips_byte_exactly`); a failure names the
//! exact fixture file. The four edge cases the review brief calls out get
//! their own named tests below so they are visible in the output.
//!
//! This file is about the ROUND TRIP only: xtask already verifies sha256
//! hashes, so re-hashing here would test the wrong thing.

use std::fs;
use std::path::{Path, PathBuf};

// thiserror is a library dependency this test target never names; the
// underscore use keeps unused_crate_dependencies (a hard error under the
// gate's -D warnings) quiet without changing behaviour.
use thiserror as _;
use toml as _;

use notes_core::{Detected, LineEnding, TextEncoding, decode, detect, round_trip, save_document};

/// The ANSI code page this gate judges the fixture corpus under; detect()
/// needs it to classify the ansi1252 fixtures, and it never changes the
/// outcome for the UTF-8/UTF-16 fixtures (they are decided before ANSI is
/// tried). The manifest declares its own ansi_codepage and the two must
/// agree (asserted in load_manifest) — a corpus authored for one code page
/// can never be judged under another without a loud failure.
const GATE_CODEPAGE: u16 = 1252;

fn fixtures_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("fixtures")
}

#[derive(serde::Deserialize)]
struct Manifest {
    ansi_codepage: u16,
    count: u32,
    files: Vec<ManifestEntry>,
}

#[derive(serde::Deserialize)]
struct ManifestEntry {
    file: String,
    encoding: String,
    line_ending: String,
    trailing_newline: bool,
    bom_present: bool,
}

/// Loads the manifest and returns it with its declared code page. A
/// missing, unreadable, empty, self-inconsistent or code-page-disagreeing
/// manifest is a HARD FAILURE — never a skip.
fn load_manifest() -> Result<(Manifest, u16), Box<dyn std::error::Error>> {
    let path = fixtures_dir().join("manifest.json");
    let text = fs::read_to_string(&path).map_err(|e| {
        format!(
            "the do-no-harm gate cannot run: manifest unreadable at {}: {e}",
            path.display()
        )
    })?;
    let manifest: Manifest = serde_json::from_str(&text)
        .map_err(|e| format!("manifest at {} does not parse: {e}", path.display()))?;
    if manifest.files.is_empty() {
        return Err(format!("manifest at {} lists no fixtures", path.display()).into());
    }
    if manifest.count as usize != manifest.files.len() {
        return Err(format!(
            "manifest inconsistency: count = {} but files = {}",
            manifest.count,
            manifest.files.len()
        )
        .into());
    }
    if manifest.ansi_codepage != GATE_CODEPAGE {
        return Err(format!(
            "the fixture corpus declares ansi_codepage {} but this gate judges it under {GATE_CODEPAGE} — the two must agree",
            manifest.ansi_codepage
        )
        .into());
    }
    let codepage = manifest.ansi_codepage;
    Ok((manifest, codepage))
}

fn read_fixture(entry: &ManifestEntry) -> Result<Vec<u8>, Box<dyn std::error::Error>> {
    let path = fixtures_dir().join(&entry.file);
    fs::read(&path).map_err(|e| format!("cannot read fixture {}: {e}", path.display()).into())
}

/// Maps the manifest vocabulary to core's types. Unknown tokens FAIL
/// LOUDLY: a silent skip would turn a manifest typo into a test that proves
/// nothing.
fn encoding_from_str(token: &str) -> Result<TextEncoding, Box<dyn std::error::Error>> {
    match token {
        "utf8" => Ok(TextEncoding::Utf8),
        "utf8bom" => Ok(TextEncoding::Utf8Bom),
        "utf16le" => Ok(TextEncoding::Utf16Le),
        "utf16be" => Ok(TextEncoding::Utf16Be),
        "ansi1252" => Ok(TextEncoding::Ansi(1252)),
        other => Err(format!("unknown encoding token {other:?} in the manifest — extend the mapping or fix the manifest").into()),
    }
}

fn line_ending_from_str(token: &str) -> Result<LineEnding, Box<dyn std::error::Error>> {
    match token {
        "lf" => Ok(LineEnding::Lf),
        "crlf" => Ok(LineEnding::CrLf),
        other => Err(format!("unknown line_ending token {other:?} in the manifest — extend the mapping or fix the manifest").into()),
    }
}

fn expected_detected(entry: &ManifestEntry) -> Result<Detected, Box<dyn std::error::Error>> {
    Ok(Detected {
        encoding: encoding_from_str(&entry.encoding)?,
        line_ending: line_ending_from_str(&entry.line_ending)?,
        trailing_newline: entry.trailing_newline,
        bom_present: entry.bom_present,
    })
}

/// A byte-level diff for failure messages: a String comparison cannot see a
/// lost CR, so mismatches are dumped as offset/hex pairs.
fn hex_diff(expected: &[u8], actual: &[u8]) -> String {
    let len = expected.len().max(actual.len());
    let diffs: Vec<usize> = (0..len)
        .filter(|&i| expected.get(i) != actual.get(i))
        .collect();
    let mut out = format!(
        "lengths: expected {} bytes vs actual {} bytes; {} differ
",
        expected.len(),
        actual.len(),
        diffs.len()
    );
    for &i in diffs.iter().take(8) {
        let e = expected
            .get(i)
            .map(|b| format!("{b:02X}"))
            .unwrap_or_else(|| "--".to_owned());
        let a = actual
            .get(i)
            .map(|b| format!("{b:02X}"))
            .unwrap_or_else(|| "--".to_owned());
        out.push_str(&format!("  {i:#08x}: expected {e} vs actual {a}\n"));
    }
    if diffs.len() > 8 {
        out.push_str(&format!(
            "  ... and {} more differing bytes\n",
            diffs.len() - 8
        ));
    }
    out
}

/// The manifest gate: every listed fixture must (1) be detected exactly as
/// the manifest says, (2) survive the pure round trip byte-for-byte, and
/// (3) survive the FULL save path — decode, atomic save_document into a
/// tempdir, re-read — byte-for-byte. One looping test over all entries; a
/// failure names the exact fixture file.
#[test]
fn every_manifest_fixture_round_trips_byte_exactly() -> Result<(), Box<dyn std::error::Error>> {
    let (manifest, codepage) = load_manifest()?;
    for entry in &manifest.files {
        let bytes = read_fixture(entry)?;
        let expected = expected_detected(entry)?;

        // (1) Detection agrees with the manifest.
        let seen = detect(&bytes, Some(codepage));
        assert_eq!(
            seen, expected,
            "{}: detection disagrees with the manifest",
            entry.file
        );

        // (2) The pure round trip is byte-identical.
        match round_trip(&bytes, Some(codepage)) {
            Ok(rt) => {
                if rt != bytes {
                    panic!(
                        "{}: pure round trip is not byte-identical\n{}",
                        entry.file,
                        hex_diff(&bytes, &rt)
                    );
                }
            }
            Err(e) => panic!("{}: round trip failed: {e}", entry.file),
        }

        // (3) The full path through the save engine is byte-identical too:
        // decode into text, atomic-save into a tempdir in the SAME detected
        // encoding (save never normalises), re-read, compare bytes.
        let text = decode(&bytes, expected)?;
        let dir = tempfile::tempdir()?;
        let target = dir.path().join("fixture-copy");
        save_document(&target, &text, expected)?;
        let saved = fs::read(&target)?;
        if saved != bytes {
            panic!(
                "{}: the save path is not byte-identical\n{}",
                entry.file,
                hex_diff(&bytes, &saved)
            );
        }
    }
    Ok(())
}

/// The ansi1252 fixtures are foreign files that are deliberately NOT valid
/// UTF-8; they must be detected as Ansi(1252) and still round-trip exactly.
#[test]
fn ansi1252_fixture_is_deliberately_not_valid_utf8() -> Result<(), Box<dyn std::error::Error>> {
    let (manifest, codepage) = load_manifest()?;
    let entry = manifest
        .files
        .iter()
        .find(|e| e.encoding == "ansi1252")
        .ok_or("the manifest has no ansi1252 fixture — the gate is incomplete")?;
    let bytes = read_fixture(entry)?;
    assert!(
        std::str::from_utf8(&bytes).is_err(),
        "{}: an ansi1252 fixture that is valid UTF-8 proves nothing",
        entry.file
    );
    let d = detect(&bytes, Some(codepage));
    assert_eq!(d.encoding, TextEncoding::Ansi(1252));
    assert_eq!(round_trip(&bytes, Some(codepage))?, bytes);
    Ok(())
}

/// The empty fixture must round-trip to ZERO bytes: writing a BOM or a
/// newline into someone's empty file is a harm.
#[test]
fn empty_fixture_round_trips_to_zero_bytes() -> Result<(), Box<dyn std::error::Error>> {
    let (manifest, codepage) = load_manifest()?;
    let entry = manifest
        .files
        .iter()
        .find(|e| e.file == "edge__empty.notes")
        .ok_or("the manifest has no edge__empty.notes fixture — the gate is incomplete")?;
    let bytes = read_fixture(entry)?;
    assert!(
        bytes.is_empty(),
        "edge__empty.notes is not empty — fixture drift"
    );
    assert_eq!(round_trip(&bytes, Some(codepage))?, bytes);
    // And the full save path writes exactly zero bytes.
    let d = detect(&bytes, Some(codepage));
    let text = decode(&bytes, d)?;
    let dir = tempfile::tempdir()?;
    let target = dir.path().join("empty.notes");
    save_document(&target, &text, d)?;
    assert_eq!(fs::read(&target)?, Vec::<u8>::new());
    Ok(())
}

/// The lone-CR fixture is a classic Mac file: detection reports the default
/// Lf for the write-back decision, and the round trip must preserve every
/// 0x0D byte without gaining an LF.
#[test]
fn lone_cr_fixture_gains_no_lf() -> Result<(), Box<dyn std::error::Error>> {
    let (manifest, codepage) = load_manifest()?;
    let entry = manifest
        .files
        .iter()
        .find(|e| e.file == "edge__lone-cr.notes")
        .ok_or("the manifest has no edge__lone-cr.notes fixture — the gate is incomplete")?;
    let bytes = read_fixture(entry)?;
    assert!(
        bytes.contains(&b'\r') && !bytes.contains(&b'\n'),
        "edge__lone-cr.notes is not a lone-CR file — fixture drift"
    );
    let d = detect(&bytes, Some(codepage));
    assert_eq!(d.line_ending, LineEnding::Lf);
    assert_eq!(round_trip(&bytes, Some(codepage))?, bytes);
    Ok(())
}

/// The frontmatter fixture is a .notes file with a '---' block; it must
/// survive detection, the pure round trip and the full save path.
#[test]
fn frontmatter_fixture_survives_the_full_save_path() -> Result<(), Box<dyn std::error::Error>> {
    let (manifest, codepage) = load_manifest()?;
    let entry = manifest
        .files
        .iter()
        .find(|e| e.file == "edge__frontmatter.notes")
        .ok_or("the manifest has no edge__frontmatter.notes fixture — the gate is incomplete")?;
    let bytes = read_fixture(entry)?;
    let text = decode(&bytes, detect(&bytes, Some(codepage)))?;
    assert!(
        text.starts_with("---"),
        "edge__frontmatter.notes lost its frontmatter block — fixture drift"
    );
    assert_eq!(round_trip(&bytes, Some(codepage))?, bytes);
    let d = detect(&bytes, Some(codepage));
    let dir = tempfile::tempdir()?;
    let target = dir.path().join("copy.notes");
    save_document(&target, &text, d)?;
    assert_eq!(fs::read(&target)?, bytes);
    Ok(())
}
